2018-08-27 23:54:35,552 ERROR: Exception on /index [POST] [in c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\jpchi\microblog\app\main\routes.py", line 27, in index
    language = guess_language(form.post.data)
NameError: name 'guess_language' is not defined
2018-08-28 00:03:27,699 ERROR: Exception on /index [POST] [in c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\jpchi\microblog\app\main\routes.py", line 27, in index
    if form.validate_on_submit():
NameError: name 'guess_language' is not defined
2018-08-28 00:24:09,726 INFO: Microblog startup [in C:\Users\jpchi\microblog\app\__init__.py:78]
2018-08-28 00:24:36,865 ERROR: Exception on /index [POST] [in c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\jpchi\microblog\app\main\routes.py", line 31, in index
    post = Post(body=form.pos.data, author=current_user, language=language)
AttributeError: 'PostForm' object has no attribute 'pos'
2018-08-28 00:25:54,561 ERROR: Exception on /index [POST] [in c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\jpchi\microblog\app\main\routes.py", line 31, in index
    post = Post(body=form.post.data, author=current_user, language=language)
AttributeError: 'PostForm' object has no attribute 'pos'
2018-08-28 00:28:13,973 INFO: Microblog startup [in C:\Users\jpchi\microblog\app\__init__.py:78]
2018-08-28 00:28:27,318 ERROR: Exception on /index [POST] [in c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\jpchi\microblog\app\main\routes.py", line 34, in index
    flask(_('Your post is now live!'))
NameError: name 'flask' is not defined
2018-08-28 00:41:16,079 INFO: Microblog startup [in C:\Users\jpchi\microblog\app\__init__.py:78]
2018-08-28 00:44:09,929 ERROR: Exception on /search [GET] [in c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\jpchi\microblog\app\main\routes.py", line 132, in search
    posts, total = post.search(g.search_form.q.data, page, current_app.config['POSTS_PER_PAGE'])
NameError: name 'post' is not defined
2018-08-28 01:02:26,433 ERROR: Exception on /search [GET] [in c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jpchi\microblog\env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\jpchi\microblog\app\main\routes.py", line 132, in search
    posts, total = Post.search(g.search_form.q.data, page, current_app.config['POSTS_PER_PAGE'])
NameError: name 'post' is not defined
2018-08-28 01:06:38,380 INFO: Microblog startup [in C:\Users\jpchi\microblog\app\__init__.py:78]
2018-08-28 01:20:53,224 INFO: Microblog startup [in C:\Users\jpchi\microblog\app\__init__.py:78]
2018-08-28 03:01:40,976 INFO: Microblog startup [in C:\Users\jpchi\microblog\app\__init__.py:78]
2018-08-28 09:29:12,731 INFO: Microblog startup [in C:\Users\jpchi\microblog\app\__init__.py:78]
2018-08-28 09:33:44,310 INFO: Microblog startup [in C:\Users\jpchi\microblog\app\__init__.py:78]
